/* groovylint-disable-next-line CompileStatic */
node {
    // This step should not normally be used in your script. Consult the inline help for details.
    withDockerContainer('python:2-alpine') {
        stage('Build') {
            checkout scm
            sh 'python -m py_compile sources/add2vals.py sources/calc.py'
        }
    }
    withDockerContainer('qnib/pytest') {
        stage('Test') {
            checkout scm
            sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
            junit 'test-reports/results.xml'
        }
    }
    stage('Manual Approval') {
        input message: 'Lanjutkan ke tahap Deploy?'
        checkout scm
    }
    stage('Deploy') {
        checkout scm
        /* groovylint-disable-next-line LineLength */
        sh 'docker run --rm -v /var/jenkins_home/workspace/submission-cicd-pipeline-mfth12-py/sources:/src cdrx/pyinstaller-linux:python2 \'pyinstaller -F add2vals.py\''
        archiveArtifacts artifacts: 'sources/add2vals.py', followSymlinks: false
        /* groovylint-disable-next-line LineLength */
        sh 'docker run --rm -v /var/jenkins_home/workspace/submission-cicd-pipeline-mfth12-py/sources:/src cdrx/pyinstaller-linux:python2 \'rm -rf build dist\''
        sleep time: 1, unit: 'MINUTES'
    }
}
